import type { NextPage } from 'next'
import Head from 'next/head'
import Team from "../components/Team";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Team />
  </>
)

export default Home